---
- name: Enable the CodeReady repo
  become: yes
  command: /usr/bin/dnf config-manager --enable codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms
  when:
    - ansible_distribution == 'RedHat'
    - not devconfig_custom_yum_repofile

- name: Enable the CodeReady repo
  become: yes
  command: /usr/bin/dnf config-manager --enable crb
  when:
    - ansible_distribution == 'CentOS'
    - not devconfig_custom_yum_repofile

- name: Install epel-release if we're not on Fedora
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  vars:
    packages:
      - epel-release
  when: ansible_distribution != "Fedora"

- name: Install docker
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  vars:
    packages:
      - docker
