---
- name: Debian-specific set up
  ansible.builtin.include_tasks: roles/tasks/nfsd/install-deps/debian/main.yml
  when: ansible_os_family == 'Debian'

- name: SuSE-specific set up
  ansible.builtin.include_tasks: roles/tasks/nfsd/install-deps/suse/main.yml
  when: ansible_os_family == 'Suse'

- name: Red Hat-specific set up
  ansible.builtin.include_tasks: roles/tasks/nfsd/install-deps/redhat/main.yml
  when: ansible_os_family == 'RedHat'
