---
- name: Import optional distribution specific variables
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ ansible_facts['os_family']|lower }}.yml"
      skip: true
  tags: vars

- name: Debian-specific setup
  include_tasks: debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: SuSE-specific setup
  include_tasks: suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'

- name: Red Hat Enterprise-specific setup
  include_tasks: redhat/main.yml
  when:
    - ansible_facts['os_family']|lower == 'redhat'
    - ansible_facts['distribution']|lower != "fedora"

- name: Fedora-specific setup
  include_tasks: fedora/main.yml
  when: ansible_facts['distribution']|lower == "fedora"
