---
kdevops_archive_data_count: 0
kdevops_results: "{{ topdir_path }}/archive"
kdevops_results_local: "{{ kdevops_results }}/{{ target_linux_ref }}/"
kdevops_results_repo_url_user: "git"
kdevops_results_repo_url: "{{ kdevops_results_repo_url_user}}@github.com:linux-kdevops/kdevops-results-archive.git"
kdevops_results_repo_url_demo: "{{ kdevops_results_repo_url_user}}@github.com:linux-kdevops/kdevops-results-archive-demo.git"
kdevops_results_repo_path: "{{ kdevops_results_repo_url.split('@')[1] }}"
kdevops_results_name: "{{ kdevops_results_repo_path.split('/')[-1] | regex_replace('\\.git$', '') }}"
kdevops_results_archive_dir: "{{ topdir_path }}/../{{ kdevops_results_name }}"
kdevops_archive_mirror_present: false
kdevops_archive_host: "{{ kdevops_results_repo_path.split(':')[0] }}"
kdevops_archive: "/mirror/{{ kdevops_results_name }}.git"
kdevops_archive_key_loaded: False
kdevops_archive_key_name: "kdevops_archive"
kdevops_archive_identity_file: "/home/gh/.ssh/{{ kdevops_archive }}"
kdevops_archive_key_detected: False
kdevops_archive_key_fingerprint: ""
kdevops_archive_key_has_passphrase: False
kdevops_archive_demo: False
bootlinux_tree_set_by_cli: False
kdevops_archive_base: "selftests/gh/linux-modules-kpd/20241021"
kdevops_archive_test_number: "0001"
kdevops_archive_prefix: "{{ kdevops_archive_base }}/{{ kdevops_archive_next_number }}/v6.12-rc4/"
