- name: debian_libaio rename for buster
  set_fact:
    is_buster: '{{ ansible_distribution_release == "buster" }}'
    is_trixie: '{{ ansible_distribution_release == "trixie" }}'

- name: debian_libaio rename for buster
  set_fact:
    pkg_libaio: "libaio1"
  when:
    - is_buster|bool
