# SPDX-License-Identifier copyleft-next-0.3.1
---
mirror_user_system_dir: "~/.config/systemd/user/"
install_linux_mirror:  False
# Please keep these in alphabetical order
defaults_blktrace_git: "https://git.kernel.dk/blktrace"
defaults_dbench_git: "https://github.com/linux-kdevops/dbench.git"
defaults_kdevops_results_archive_git: "https://github.com/linux-kdevops/kdevops-results-archive.git"
defaults_git_git: "https://git.kernel.org/pub/scm/git/git.git"
defaults_ltp_git: "https://github.com/linux-test-project/ltp.git"
defaults_nfstest_git: "git://git.linux-nfs.org/projects/mora/nfstest.git"
defaults_xfsprogs_git: "https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git"
defaults_xfsdump_git: "https://github.com/linux-kdevops/xfsdump-dev.git"
