---

- name: create a region from cxl memory
  become: yes
  command: "cxl create-region -m -d decoder0.0 -w 1 mem0 -s 256M"
  tags: [ 'cxl-mem-setup' ]

- name: create a namespace from cxl memory
  become: yes
  command: "ndctl create-namespace -m dax -r region0"
  tags: [ 'cxl-mem-setup' ]

- name: switch daxdevice to be used for system-ram
  become: yes
  command: "daxctl reconfigure-device --mode=system-ram --no-online dax0.0"
  tags: [ 'cxl-mem-setup' ]

- name: online newly created daxdevice
  become: yes
  command: "daxctl online-memory dax0.0"
  tags: [ 'cxl-mem-setup' ]


