---
- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: linux

- name: Install generic kdevops deps
  become: yes
  become_method: sudo
  apt:
    name:
      - gcc
      - make
      - bison
      - flex
      - m4
      - bc
      - sed
      - libncurses-dev
    state: present
    update_cache: yes
  tags: [ 'kdevops', 'deps' ]
