---
- name: Install systemd-journal-remote
  become: yes
  become_method: sudo
  apt:
    name:
      - systemd-journal-remote
  when:
    - devconfig_enable_systemd_journal_remote|bool
  tags: journal
