---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Install dependencies for the linux-mirror role
  ansible.builtin.include_tasks: install-deps/fedora/main.yml
  when:
    - ansible_distribution == 'Fedora'
  tags: [ 'mirror' ]

- name: Set up the mirrors.yaml based on preferences configured
  tags: [ 'mirror' ]
  template:
    src: "mirrors.yaml.j2"
    dest: "{{ topdir_path }}/playbooks/roles/linux-mirror/linux-mirror-systemd/mirrors.yaml"
    force: yes
    trim_blocks: True
    lstrip_blocks: True
  when:
    - install_linux_mirror|bool

- name: Set up the git daemon systemd service and socket files
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  template:
    src: "{{ item }}.j2"
    dest: "{{ local_systemd_path }}/{{ item }}"
    force: yes
    trim_blocks: True
    lstrip_blocks: True
  with_items:
    - "git-daemon@.service"
    - "git-daemon.socket"
  when:
    - install_linux_mirror|bool
  tags: [ 'mirror' ]

- name: Start mirroring
  delegate_to: localhost
  run_once: true
  shell: |
    set -o pipefail
    {{ role_path }}/python/start-mirroring.py --verbose
  args:
    executable: /bin/bash
    chdir: "{{ topdir_path }}"
  when:
    - install_linux_mirror|bool
  tags: [ 'mirror' ]

- name: Generate systemd service and timer unit files
  delegate_to: localhost
  run_once: true
  shell: |
    set -o pipefail
    {{ role_path }}/python/gen-mirror-files.py --refresh 360m --refresh-on-boot 10m
  args:
    executable: /bin/bash
    chdir: "{{ topdir_path }}"
  when:
    - install_linux_mirror|bool
  tags: [ 'mirror' ]

- name: load variables from yaml file
  include_vars:
    file: "{{ topdir_path }}/playbooks/roles/linux-mirror/linux-mirror-systemd/mirrors.yaml"
    name: mirrors
  tags: [ 'mirror' , 'status-check' ]

- name: Set scope based on user (root uses system scope)
  set_fact:
    systemd_scope: "{{ 'system' if ansible_user_id == 'root' else 'user' }}"
    systemd_dir: "{{ '/etc/systemd/system/' if ansible_user_id == 'root' else mirror_user_system_dir }}"
  tags: [ 'mirror' ]

- name: Copy systemd service file to user/system systemd dir
  copy:
    src: "{{ topdir_path }}/playbooks/roles/linux-mirror/linux-mirror-systemd/{{ item.short_name | regex_replace('/', '-') }}-mirror.service"
    dest: "{{ systemd_dir }}/"
  with_items:
    - "{{ mirrors.get('mirrors') }}"
  loop_control:
    label: "Installing {{ item.short_name }}-mirror.service unit ..."
  tags: [ 'mirror' ]

- name: Copy systemd timer file to user/system systemd dir
  copy:
    src: "{{ topdir_path }}/playbooks/roles/linux-mirror/linux-mirror-systemd/{{ item.short_name | regex_replace('/', '-') }}-mirror.timer"
    dest: "{{ systemd_dir }}/"
  with_items:
    - "{{ mirrors.get('mirrors') }}"
  loop_control:
    label: "Installing {{ item.short_name }}-mirror.timer unit ..."
  tags: [ 'mirror' ]

- name: Enable systemd unit for mirror services
  ansible.builtin.systemd_service:
    name: "{{ item.short_name | regex_replace('/', '-') }}-mirror.service"
    state: started
    enabled: true
    scope: "{{ systemd_scope }}"
  with_items:
    - "{{ mirrors.get('mirrors') }}"
  loop_control:
    label: "Enabling {{ item.short_name }}-mirror.service unit ..."
  tags: [ 'mirror' ]

- name: Enable systemd unit for mirror timers
  ansible.builtin.systemd_service:
    name: "{{ item.short_name | regex_replace('/', '-') }}-mirror.timer"
    state: started
    enabled: true
    scope: "{{ systemd_scope }}"
  with_items:
    - "{{ mirrors.get('mirrors') }}"
  loop_control:
    label: "Enabling {{ item.short_name }}-mirror.timer unit ..."
  tags: [ 'mirror' ]

- name: Check systemd unit status for mirror services
  ansible.builtin.systemd_service:
    name: "{{ item.short_name | regex_replace('/', '-') }}-mirror.service"
    scope: user
  register: mirror_service_status
  with_items:
    - "{{ mirrors.get('mirrors') }}"
  loop_control:
    label: "Checking service status for {{ item.short_name | regex_replace('/', '-') }}-mirror.service unit ..."
  tags: [ 'status-check' ]

- name: Service status
  debug:
    var: "{{ item }}.status.ActiveState"
  with_items:
    - "{{ mirror_service_status.item }}"
  tags: [ 'status-check' ]

- name: Check systemd unit status for mirror timers
  ansible.builtin.systemd_service:
    name: "{{ item.short_name | regex_replace('/', '-') }}-mirror.timer"
    scope: user
  register: mirror_timer_status
  with_items:
    - "{{ mirrors.get('mirrors') }}"
  loop_control:
    label: "Checking service status for {{ item.short_name | regex_replace('/', '-') }}--mirror.timer ..."
  tags: [ 'status-check' ]

- name: Service timer status
  debug:
    var: "{{ item }}.status.ActiveState"
  with_items:
    - "{{ mirror_timer_status.item }}"
  tags: [ 'status-check' ]

- name: Enable git service systemd socket activation
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.systemd_service:
    name: "git-daemon.socket"
    state: started
    enabled: true
  tags: [ 'mirror' ]
