name: Run kdevops on self-hosted runner

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:  # Add this for manual triggering of the workflow

jobs:
  run-kdevops:
    name: Run kdevops CI
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config --global --add safe.directory '*'

      - name: Run kdevops make defconfig-repo
        run: |
          make KDEVOPS_HOSTS_PREFIX="gh" defconfig-xfs_reflink_4k

      - name: Run kdevops make
        run: |
          make -j$(nproc)

      - name: Run kdevops make bringup
        run: |
          make bringup

      - name: Build linux and boot test nodes on test kernel
        run: |
          make linux

      - name: Build fstests
        run: |
          make fstests

      - name: Run just one fstest to verify we tests and test collection works
        run: |
          make fstests-baseline TESTS=generic/003

      - name: Get systemd journal files
        if: always() # This ensures the step runs even if previous steps failed
        run: |
          cd kdevops
          make journal-dump

      - name: Build our kdevops archive results
        if: always() # This ensures the step runs even if previous steps failed
        run: |
          cd kdevops
          make ci-archive

      - name: Find and kdevops results zip file
        if: always() # This ensures the step runs even if previous steps failed
        run: |
          ZIP_FILE=$(find kdevops/archive -name "*.zip" -type f | head -n 1)
          echo "Found zip file: $ZIP_FILE"
          echo "KDEVOPS_ARTIFACT_PATH=$ZIP_FILE" >> $GITHUB_ENV

      - name: Upload our kdevops results archive
        if: always() # This ensures the step runs even if previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: kdevops-ci-results
          path: ${{ env.KDEVOPS_ARTIFACT_PATH }}

      # Ensure make destroy always runs, even on failure
      - name: Run kdevops make destroy
        if: always()  # This ensures the step runs even if previous steps failed
        run: |
          make destroy
