---
ltp_packages:
  - gcc
  - git
  - make
  - pkgconf
  - autoconf
  - automake
  - bison
  - flex
  - m4
  - ethtool
  - nfs-common
  - nfs-kernel-server
  - libc6-dev
  - rpcbind
  - libtirpc-dev
  - libssl-dev
